const carNames = [
  'Toyota Camry',
  'Honda Civic',
  'Ford Mustang',
  'Chevrolet Corvette',
  'BMW 3 Series',
  'Mercedes-Benz C-Class',
  'Audi A4',
  'Volkswagen Golf',
  'Nissan Altima',
  'Subaru Impreza',
  'Hyundai Elantra',
  'Kia Optima',
  'Mazda3',
  'Lexus ES',
  'Acura TLX',
  'Infiniti Q50',
  'Volvo S60',
  'Jaguar XE',
  'Porsche 911',
  'Tesla Model S',
  'Chevrolet Silverado',
  'Ford F-150',
  'GMC Sierra',
  'Ram 1500',
  'Toyota Tacoma',
  'Honda Ridgeline',
  'Nissan Titan',
  'Jeep Wrangler',
  'Subaru Outback',
  'Ford Explorer',
  'Chevrolet Traverse',
  'Toyota Highlander',
  'Honda Pilot',
  'Mazda CX-9',
  'Hyundai Santa Fe',
  'Kia Sorento',
  'Volkswagen Atlas',
  'BMW X5',
  'Mercedes-Benz GLE',
  'Audi Q7',
  'Lexus RX',
  'Acura MDX',
  'Infiniti QX60',
  'Volvo XC90',
  'Jaguar F-Pace',
  'Porsche Cayenne',
  'Tesla Model X',
  'Chevrolet Bolt',
  'Nissan Leaf',
  'Toyota Prius',
  'Honda Accord Hybrid',
  'Ford Fusion Hybrid',
  'Hyundai Ioniq Electric',
  'Kia Soul EV',
  'BMW i3',
  'Mercedes-Benz EQC',
  'Audi e-tron',
  'Lexus UX Hybrid',
  'Acura NSX',
  'Infiniti Q60',
  'Volvo V60',
  'Jaguar XF',
  'Porsche Panamera',
  'Tesla Model 3',
  'Chevrolet Camaro',
  'Ford Mustang Mach-E',
  'GMC Hummer EV',
  'Ram 2500',
  'Toyota Tundra',
  'Honda Passport',
  'Nissan Rogue',
  'Subaru Forester',
  'Hyundai Tucson',
  'Kia Sportage',
  'Volkswagen Tiguan',
  'BMW X3',
  'Mercedes-Benz GLC',
  'Audi Q5',
  'Lexus NX',
  'Acura RDX',
  'Infiniti QX50',
  'Volvo XC60',
  'Jaguar E-Pace',
  'Porsche Macan',
  'Tesla Model Y',
  'Chevrolet Equinox',
  'Ford Escape',
  'GMC Terrain',
  'Ram 3500',
  'Toyota 4Runner',
  'Honda CR-V',
  'Nissan Murano',
  'Subaru Crosstrek',
  'Hyundai Kona',
  'Kia Niro',
  'Volkswagen ID.4',
  'BMW X1',
  'Mercedes-Benz GLA',
  'Audi Q3',
  'Lexus GX',
];

const hexNumbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'];

export { carNames, hexNumbers };
