const carNames = [
  'Audi A4',
  'BMW 3 Series',
  'Mercedes-Benz C-Class',
  'Volkswagen Golf',
  'Ford Focus',
  'Toyota Corolla',
  'Honda Civic',
  'Nissan Sentra',
  'Chevrolet Cruze',
  'Hyundai Elantra',
  'Kia Forte',
  'Mazda3',
  'Subaru Impreza',
  'Volvo S60',
  'Lexus IS',
  'Acura ILX',
  'Infiniti Q50',
  'Cadillac ATS',
  'Lincoln MKZ',
  'Buick Regal',
  'Jaguar XE',
  'Land Rover Range Rover Evoque',
  'Porsche Panamera',
  'Tesla Model 3',
  'Fiat 500',
  'Alfa Romeo Giulia',
  'Peugeot 308',
  'Renault Megane',
  'Citroen C4',
  'Opel Astra',
  'Seat Leon',
  'Skoda Octavia',
  'Volkswagen Passat',
  'Ford Mondeo',
  'Toyota Camry',
  'Honda Accord',
  'Nissan Altima',
  'Chevrolet Malibu',
  'Hyundai Sonata',
  'Kia Optima',
  'Mazda6',
  'Subaru Legacy',
  'Volvo S90',
  'Lexus ES',
  'Acura TLX',
  'Infiniti Q70',
  'Cadillac CTS',
  'Lincoln Continental',
  'Buick LaCrosse',
  'Jaguar XF',
  'Land Rover Range Rover Sport',
  'Porsche 911',
  'Tesla Model S',
  'Fiat Tipo',
  'Alfa Romeo Stelvio',
  'Peugeot 508',
  'Renault Talisman',
  'Citroen C5',
  'Opel Insignia',
  'Seat Exeo',
  'Skoda Superb',
  'Volkswagen Arteon',
  'Ford Fusion',
  'Toyota Avalon',
  'Honda Clarity',
  'Nissan Maxima',
  'Chevrolet Impala',
  'Hyundai Azera',
  'Kia Cadenza',
  'Mazda6',
  'Subaru Outback',
  'Volvo V90',
  'Lexus GS',
  'Acura RLX',
  'Infiniti QX50',
  'Cadillac XT5',
  'Lincoln MKC',
  'Buick Envision',
  'Jaguar F-Pace',
  'Land Rover Discovery Sport',
  'Porsche Macan',
  'Tesla Model X',
  'Fiat 500L',
  'Alfa Romeo 4C',
  'Peugeot 3008',
  'Renault Koleos',
  'Citroen C-Crosser',
  'Opel Crossland X',
  'Seat Ateca',
  'Skoda Karoq',
  'Volkswagen Tiguan',
  'Ford Escape',
  'Toyota RAV4',
  'Honda CR-V',
  'Nissan Rogue',
  'Chevrolet Equinox',
  'Hyundai Tucson',
  'Kia Sportage',
  'Mazda CX-5',
  'Subaru Forester',
  'Volvo XC60',
  'Lexus NX',
  'Acura RDX',
  'Infiniti QX60',
  'Cadillac XT6',
  'Lincoln Nautilus',
  'Buick Encore',
  'Jaguar E-Pace',
  'Land Rover Range Rover Velar',
  'Porsche Cayenne',
  'Tesla Model Y',
  'Fiat 500X',
  'Alfa Romeo Giulietta',
  'Peugeot 2008',
  'Renault Captur',
  'Citroen C3 Aircross',
  'Opel Mokka X',
  'Seat Arona',
  'Skoda Kamiq',
  'Volkswagen T-Roc',
  'Ford EcoSport',
  'Toyota C-HR',
  'Honda HR-V',
  'Nissan Juke',
  'Chevrolet Trax',
  'Hyundai Kona',
  'Kia Soul',
  'Mazda CX-3',
  'Subaru XV',
  'Volvo XC40',
  'Lexus UX',
  'Acura MDX',
  'Infiniti QX60',
  'Cadillac XT6',
  'Lincoln Nautilus',
  'Buick Encore',
  'Jaguar E-Pace',
  'Land Rover Range Rover Velar',
  'Porsche Cayenne',
  'Tesla Model Y',
  'Fiat 500X',
  'Alfa Romeo Giulietta',
  'Peugeot 2008',
  'Renault Captur',
  'Citroen C3 Aircross',
  'Opel Mokka X',
  'Seat Arona',
  'Skoda Kamiq',
  'Volkswagen T-Roc',
  'Ford EcoSport',
  'Toyota C-HR',
  'Honda HR-V',
  'Nissan Juke',
  'Chevrolet Trax',
  'Hyundai Kona',
  'Kia Soul',
  'Mazda CX-3',
  'Subaru XV',
  'Volvo XC40',
  'Lexus UX',
  'Acura MDX',
  'Infiniti QX60',
  'Cadillac XT6',
  'Lincoln Nautilus',
  'Buick Encore',
  'Jaguar E-Pace',
  'Land Rover Range Rover Velar',
  'Porsche Cayenne',
  'Tesla Model Y',
  'Fiat 500X',
  'Alfa Romeo Giulietta',
  'Peugeot 2008',
  'Renault Captur',
  'Citroen C3 Aircross',
  'Opel Mokka X',
  'Seat Arona',
  'Skoda Kamiq',
  'Volkswagen T-Roc',
  'Ford EcoSport',
  'Toyota C-HR',
  'Honda HR-V',
  'Nissan Juke',
  'Chevrolet Trax',
  'Hyundai Kona',
  'Kia Soul',
  'Mazda CX-3',
  'Subaru XV',
  'Volvo XC40',
  'Lexus UX',
  'Acura MDX',
  'Infiniti QX60',
  'Cadillac XT6',
  'Lincoln Nautilus',
  'Buick Encore',
  'Jaguar E-Pace',
  'Land Rover Range Rover Velar',
  'Porsche Cayenne',
  'Tesla Model Y',
  'Fiat 500X',
  'Alfa Romeo Giulietta',
  'Peugeot 2008',
  'Renault Captur',
  'Citroen C3 Aircross',
  'Opel Mokka X',
  'Seat Arona',
  'Skoda Kamiq',
  'Volkswagen T-Roc',
  'Ford EcoSport',
  'Toyota C-HR',
  'Honda HR-V',
  'Nissan Juke',
  'Chevrolet Trax',
  'Hyundai Kona',
  'Kia Soul',
  'Mazda CX-3',
  'Subaru XV',
  'Volvo XC40',
  'Lexus UX',
  'Acura MDX',
  'Infiniti QX60',
  'Cadillac XT6',
  'Lincoln Nautilus',
  'Buick Encore',
  'Jaguar E-Pace',
  'Land Rover Range Rover Velar',
  'Porsche Cayenne',
  'Tesla Model Y',
  'Fiat 500X',
  'Alfa Romeo Giulietta',
  'Peugeot 2008',
  'Renault Captur',
  'Citroen C3 Aircross',
  'Opel Mokka X',
  'Seat Arona',
  'Skoda Kamiq',
  'Volkswagen T-Roc',
  'Ford EcoSport',
  'Toyota C-HR',
  'Honda HR-V',
  'Nissan Juke',
  'Chevrolet Trax',
  'Hyundai Kona',
  'Kia Soul',
  'Mazda CX-3',
  'Subaru XV',
  'Volvo XC40',
  'Lexus UX',
  'Acura MDX',
  'Infiniti QX60',
  'Cadillac XT6',
  'Lincoln Nautilus',
  'Buick Encore',
  'Jaguar E-Pace',
  'Land Rover Range Rover Velar',
  'Porsche Cayenne',
  'Tesla Model Y',
  'Fiat 500X',
  'Alfa Romeo Giulietta',
  'Peugeot 2008',
  'Renault Captur',
  'Citroen C3 Aircross',
  'Opel Mokka X',
  'Seat Arona',
  'Skoda Kamiq',
  'Volkswagen T-Roc',
  'Ford EcoSport',
  'Toyota C-HR',
  'Honda HR-V',
  'Nissan Juke',
  'Chevrolet Trax',
  'Hyundai Kona',
  'Kia Soul',
  'Mazda CX-3',
  'Subaru XV',
  'Volvo XC40',
  'Lexus UX',
  'Acura MDX',
  'Infiniti QX60',
  'Cadillac XT6',
  'Lincoln Nautilus',
  'Buick Encore',
  'Jaguar E-Pace',
  'Land Rover Range Rover Velar',
  'Porsche Cayenne',
  'Tesla Model Y',
  'Fiat 500X',
  'Alfa Romeo Giulietta',
  'Peugeot 2008',
  'Renault Captur',
  'Citroen C3 Aircross',
  'Opel Mokka X',
  'Seat Arona',
  'Skoda Kamiq',
  'Volkswagen T-Roc',
  'Ford EcoSport',
  'Toyota C-HR',
  'Honda HR-V',
  'Nissan Juke',
  'Chevrolet Trax',
  'Hyundai Kona',
  'Kia Soul',
  'Mazda CX-7',
];

const hexNumbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'];

export { carNames, hexNumbers };
